[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"
authors = ["David Bauer <david.bauer009@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time-test = "0.2.2"
itertools = "0.9.0"
